/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.badpals.stockx;

import edu.badpals.stockx.item.Sneaker;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Sneaker zapa = new Sneaker();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
